version: '3.8'

services:
  api:
    image: ${APP_IMAGE:-financia-api:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8102:8000"
    env_file:
      - .env
    networks:
      - levius-network

networks:
  levius-network:
    driver: bridge