[supervisord]
nodaemon=true
user=root

[program:alembic]
command=alembic upgrade head
autorestart=false
priority=1
startsecs=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:mcp]
command=python mcp_server.py
autostart=true
autorestart=true
priority=10
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:uvicorn]
command=uvicorn api_server:app --host 0.0.0.0 --port 8080 --ws websockets
autostart=true
autorestart=true
priority=10
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
